"use client";

import type { ColumnDef } from "@tanstack/react-table";
import { Download, MoreVertical, Star } from "lucide-react";
import { ComparisonBarChart, ComparisonLineChart, DonutChart } from "@/components/shared/AdminCharts";
import { AdminDataTable } from "@/components/shared/AdminDataTable";
import {
  InitialAvatar,
  MetricGrid,
  SectionHeader,
  SoftTag,
} from "@/components/shared/AdminPrimitives";
import { CardShell } from "@/components/shared/CardShell";
import { PageHeader } from "@/components/shared/PageHeader";
import { Button } from "@/components/ui/button";
import {
  platformOverview,
  providerPerformance,
  recentReports,
  reportsCategoryRevenue,
  reportsJobStatus,
  reportsJobsTrend,
  reportsMetrics,
  reportsRevenue,
} from "@/lib/mock-data";
import { cn } from "@/lib/utils";

type ReportRow = (typeof recentReports)[number];

const categoryTone: Record<string, string> = {
  Financial: "green",
  Job: "blue",
  User: "purple",
  Provider: "amber",
};

const reportColumns: ColumnDef<ReportRow>[] = [
  { accessorKey: "name", header: "Report Name", cell: ({ row }) => <span className="font-bold">{row.original.name}</span> },
  { accessorKey: "category", header: "Category", cell: ({ row }) => <SoftTag tone={categoryTone[row.original.category]}>{row.original.category}</SoftTag> },
  { accessorKey: "generatedOn", header: "Generated On" },
  { accessorKey: "generatedBy", header: "Generated By" },
  { accessorKey: "format", header: "Format", cell: ({ row }) => <span className="font-black text-primary">{row.original.format}</span> },
  {
    id: "actions",
    header: "Actions",
    cell: () => (
      <div className="flex gap-2">
        <Button variant="outline" size="icon" className="h-8 w-8 bg-card" aria-label="Download report">
          <Download className="h-4 w-4" />
        </Button>
        <Button variant="outline" size="icon" className="h-8 w-8 bg-card" aria-label="More report actions">
          <MoreVertical className="h-4 w-4" />
        </Button>
      </div>
    ),
  },
];

export default function ReportsAnalyticsPage() {
  const maxCategory = Math.max(...reportsCategoryRevenue.map((item) => item.value));

  return (
    <div className="mx-auto max-w-[1600px] space-y-5">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
        <PageHeader title="Reports & Analytics" subtitle="Track platform performance and key metrics in real time." />
        <div className="flex rounded-xl border bg-card p-1">
          {["7D", "30D", "90D", "YTD"].map((range, index) => (
            <Button key={range} variant={index === 0 ? "secondary" : "ghost"} className="h-9 rounded-lg px-4">
              {range}
            </Button>
          ))}
        </div>
      </div>

      <MetricGrid metrics={reportsMetrics} />

      <section className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_420px]">
        <CardShell className="p-4">
          <div className="mb-4 flex items-center justify-between gap-3">
            <h2 className="text-base font-black">Revenue Overview</h2>
            <Button variant="outline" className="bg-card">
              Daily
            </Button>
          </div>
          <div className="mb-2 flex justify-end gap-4 text-xs font-bold text-muted-foreground">
            <span className="flex items-center gap-2"><span className="h-0.5 w-6 bg-blue-600" />This Period</span>
            <span className="flex items-center gap-2"><span className="h-0.5 w-6 border-t border-dashed border-slate-500" />Previous Period</span>
          </div>
          <ComparisonLineChart data={reportsRevenue} />
        </CardShell>

        <CardShell className="p-4">
          <SectionHeader title="Jobs by Status" action="View Details" />
          <div className="grid gap-3 sm:grid-cols-[180px_1fr] xl:grid-cols-1">
            <DonutChart data={reportsJobStatus} total="1,248" label="Total Jobs" height={190} />
            <div className="space-y-3">
              {reportsJobStatus.map((item) => (
                <div key={item.name} className="flex items-center justify-between gap-3 text-sm">
                  <span className="flex items-center gap-2 font-semibold">
                    <span className="h-3 w-3 rounded-full" style={{ backgroundColor: item.color }} />
                    {item.name}
                  </span>
                  <span className="font-black">
                    {item.value} ({item.percent})
                  </span>
                </div>
              ))}
            </div>
          </div>
        </CardShell>
      </section>

      <section className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_420px]">
        <div className="grid gap-4 lg:grid-cols-2">
          <CardShell className="p-4">
            <div className="mb-4 flex items-center justify-between">
              <h2 className="text-base font-black">Jobs Trend</h2>
              <Button variant="outline" className="bg-card">Daily</Button>
            </div>
            <ComparisonBarChart data={reportsJobsTrend} />
          </CardShell>

          <CardShell className="p-4">
            <SectionHeader title="Revenue by Service Category" action="View Details" />
            <div className="space-y-4">
              {reportsCategoryRevenue.map((item) => (
                <div key={item.category} className="grid grid-cols-[150px_minmax(100px,1fr)_92px] items-center gap-3 text-sm">
                  <span className="truncate font-semibold text-muted-foreground">{item.category}</span>
                  <div className="h-3 rounded-full bg-muted">
                    <div className="h-full rounded-full bg-blue-600" style={{ width: `${(item.value / maxCategory) * 100}%` }} />
                  </div>
                  <span className="text-right font-black">GHS {item.value.toLocaleString()}</span>
                </div>
              ))}
            </div>
          </CardShell>
        </div>

        <CardShell className="p-4">
          <SectionHeader title="Top Performing Providers" />
          <div className="space-y-4">
            {providerPerformance.map((provider) => (
              <div key={provider.provider} className="grid grid-cols-[36px_1fr_54px_92px_58px] items-center gap-3 text-sm">
                <InitialAvatar initials={provider.initials} className="bg-black text-white" />
                <span className="font-bold">{provider.provider}</span>
                <span className="font-black">{provider.jobs}</span>
                <span className="font-bold">{provider.revenue}</span>
                <span className="font-black">
                  {provider.rating} <Star className="inline h-3.5 w-3.5 fill-amber-400 text-amber-400" />
                </span>
              </div>
            ))}
          </div>
        </CardShell>
      </section>

      <section className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_420px]">
        <CardShell className="p-4">
          <h2 className="mb-4 text-base font-black">Recent Reports</h2>
          <AdminDataTable data={recentReports} columns={reportColumns} minWidth="900px" />
          <Button variant="link" className="mt-4 h-auto p-0 font-black">
            View All Reports
          </Button>
        </CardShell>

        <CardShell className="p-4">
          <h2 className="text-base font-black">Platform Overview</h2>
          <div className="mt-4 grid gap-4 sm:grid-cols-2">
            {platformOverview.map((item) => {
              const Icon = item.icon;
              const down = item.direction === "down";
              return (
                <div key={item.label} className="rounded-2xl border p-4">
                  <div className="flex items-center gap-3">
                    <span
                      className={cn(
                        "grid h-10 w-10 place-items-center rounded-xl",
                        item.tone === "blue" && "bg-blue-100 text-blue-700 dark:bg-blue-500/15",
                        item.tone === "green" && "bg-green-100 text-green-700 dark:bg-green-500/15",
                        item.tone === "red" && "bg-red-100 text-red-700 dark:bg-red-500/15",
                      )}
                    >
                      <Icon className="h-5 w-5" />
                    </span>
                    <div>
                      <p className="text-xs font-semibold text-muted-foreground">{item.label}</p>
                      <p className="text-xl font-black">{item.value}</p>
                    </div>
                  </div>
                  <p className={cn("mt-3 text-xs font-black", down ? "text-red-600" : "text-green-600")}>
                    {down ? "Down" : "Up"} {item.change}
                  </p>
                </div>
              );
            })}
          </div>
          <p className="mt-4 text-sm text-muted-foreground">vs May 5 - May 11, 2025</p>
        </CardShell>
      </section>
    </div>
  );
}
